spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://zipkin:9411
#    zipkin the container name
server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
