server:
  port: 8090

spring:
  application:
    name: customer
  datasource:
    username: hyt
    url: jdbc:postgresql://localhost:5432/customer
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

  rabbitmq:
    addresses: localhost:5672

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka