server:
  port: 8088

spring:
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
#    zipkin is the container

  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
#        - id: fraud
#          uri: lb://FRAUD
#          predicates:
#            - Path=/api/v1/fraud/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
